"""Update database schema

Revision ID: 409e7a93b342
Revises: 
Create Date: 2025-11-01 16:07:06.329089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409e7a93b342'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_phone_number', ['phone_number'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_unique_constraint('uq_vendor_business_shortcode', ['business_shortcode'])
        batch_op.create_unique_constraint('uq_vendor_email', ['email'])
        batch_op.create_unique_constraint('uq_vendor_phone', ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint('uq_vendor_phone', type_='unique')
        batch_op.drop_constraint('uq_vendor_email', type_='unique')
        batch_op.drop_constraint('uq_vendor_business_shortcode', type_='unique')
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_phone_number', type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_column('is_active')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
