"""Update database schema

Revision ID: fa0c6f002828
Revises: 409e7a93b342
Create Date: 2025-11-05 16:28:19.293763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0c6f002828'
down_revision = '409e7a93b342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_payment_sessions_transaction_id', 'transactions', ['transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_sessions_transaction_id', type_='foreignkey')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
